# Generated by Django 3.2.11 on 2022-01-16 13:19

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remindermodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remindermodel',
            name='slug',
            field=slugger.fields.AutoSlugField(populate_from='title'),
        ),
    ]
